name: tests-and-publish
# this pipeline started as an adaptation of the pipeline of the
# FlexMeasures client (https://github.com/FlexMeasures/flexmeasures-client/)

on:
  push:
    # Avoid using all the resources/limits available by checking only
    # relevant branches and tags. Other branches can be checked via PRs.
    branches: [main]
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+'  # Match tags that resemble a version
      - 'v[0-9]+\.[0-9]+\.[0-9]+'  # Match tags that resemble a version
  pull_request:  # Run in every PR
  workflow_dispatch:  # Allow manually triggering the workflow
  schedule:
    # Run roughly every 15 days at 00:00 UTC
    # (useful to check if updates on dependencies break the package)
    - cron: '0 0 1,16 * *'

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  checks:
    strategy:
      matrix:
        include:
          - python: "3.9"
            release: true
          - python: "3.10"
          - python: "3.11"
          - python: "3.12"
          - python: "3.13"
    uses: ./.github/workflows/check-python.yml
    with:
      python-version: ${{ matrix.python }}
      release-artifact: ${{ matrix.release || false }}

  finalize:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - run: echo "Finished checks"

  publish:
    needs: finalize
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/s2-python/
    permissions:
      id-token: write
    steps:
      - name: Retrieve pre-built distribution files
        uses: actions/download-artifact@v4
        with: {name: python-distribution-files, path: dist/}
      - name: Publish Package
        uses: pypa/gh-action-pypi-publish@release/v1
        # run: pipx run tox -e publish

  test-publish:
    needs: finalize
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/test') }}
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/s2-python/
    permissions:
      id-token: write
    steps:
      - name: Retrieve pre-built distribution files
        uses: actions/download-artifact@v4
        with: {name: python-distribution-files, path: dist/}
      - name: Publish Package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
        # run: pipx run tox -e publish
